ALTER TABLE jobs ADD COLUMN IF NOT EXISTS has_invoice BOOLEAN DEFAULT FALSE;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_total REAL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_rebate_amount REAL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_paid_amount REAL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_balance REAL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS st_invoice_id TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_date TIMESTAMP;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_paid_on TIMESTAMP;
